on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - ".scafflater/**"
    types: [opened, synchronize, reopened]
  workflow_dispatch:

name: Standard
permissions:
  contents: read

jobs:
  ci:
    name: CI - Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Python Cache
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/Python/
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: poetry-
      - name: Install Dependencies Python
        run: make dev-dependencies
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Test
        run: make test-coverage
      - name: Lint
        run: make lint
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
